## create chats
POST http://localhost:8090/api/rag/v1/createChat HTTP/1.1
Content-Type: application/json

{
    "usuario": "manolo",
    "contexto": 8
 }

#########

POST http://localhost:8090/api/rag/v1/createQuestionChat HTTP/1.1
Content-Type: application/json

{
    "idChat": 27,
    "usuario": "manolo",
    "textoPregunta": "prueba" 
}


#########/////

GET http://localhost:8090/api/rag/v1/returnPreguntasByIdChat?idChat=27 HTTP/1.1

#########/////

GET http://localhost:8090/api/rag/v1/returnChatsInfo HTTP/1.1

##########

GET http://localhost:8090/api/rag/v1/returnChatInfo?idChat=27 HTTP/1.1

#########/////

DELETE  http://localhost:8090/api/rag/v1/deleteChat?idChat=23 HTTP/1.1

##########

PUT http://localhost:8090/api/rag/v1/updatePregunta/27 HTTP/1.1
Content-Type: application/json

{
    "idChat": 27,
    "idPregunta": 27,
    "usuario": "manolo",
    "textoPregunta": "prueba" ,
    "textoRespuesta": "Adios",
    "feedback": "MAL",
    "valorado": true
    
}
#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=filtro&filterBy=user&valor1=manolo&filterBy2=texto_pregunta&valor2=Hola HTTP/1.1

    ///chats/filter?operacion=filtro&filterBy=user&valor1=manolo

#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=rango&filterBy=fecha&valor1=2025-02-05 HTTP/1.1
#######
GET http://localhost:8090/api/rag/v1/chats/filter?operacion=count&filterBy=user&valor1=manolo  HTTP/1.1

#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=count&filterBy=user&valor1=Usuar2  HTTP/1.1


###
## returnChats
GET http://localhost:8090/api/rag/v1/returnChats? HTTP/1.1
Content-Type: application/json
###

###
##  returnChats con size
GET http://localhost:8090/api/rag/v1/returnChats?size=10 HTTP/1.1
Content-Type: application/json

###
##  returnChats con size
GET http://localhost:8090/api/rag/v1/returnChats?page=1 HTTP/1.1
Content-Type: application/json
######
## #
//return lista de users con distinct
GET http://localhost:8090/api/rag/v1/getListUsuarios HTTP/1.1
Content-Type: application/json

######
## #
//return lista de contextos con su count
GET http://localhost:8090/api/rag/v1/contexto/popular HTTP/1.1
Content-Type: application/json


#####

########

POST http://localhost:8090/api/rag/v1/filter HTTP/1.1
Content-Type: application/json

{

}


########


POST http://localhost:8090/api/rag/v1/estadisticas?groupBy=contexto&historic=true HTTP/1.1
Content-Type: application/json

{


}
