## create chats
POST http://localhost:8090/api/rag/v1/createChat HTTP/1.1
Content-Type: application/json

{
    "usuario": "manolo",
    "contexto": 1
 }

#########

POST http://localhost:8090/api/rag/v1/createQuestionChat HTTP/1.1
Content-Type: application/json

{
    "idChat": 7,
    "usuario": "manolo",
    "textoPregunta": "hola" 
}


#########/////

GET http://localhost:8090/api/rag/v1/returnPreguntasByIdChat?idChat=2 HTTP/1.1


#########/////

GET http://localhost:8090/api/rag/v1/returnChatsInfo HTTP/1.1

##########

GET http://localhost:8090/api/rag/v1/returnChatInfo?idChat=3 HTTP/1.1

#########/////

DELETE  http://localhost:8090/api/rag/v1/deleteChat?idChat=5 HTTP/1.1

##########

PUT http://localhost:8090/api/rag/v1/updatePregunta/5 HTTP/1.1
Content-Type: application/json

{
    "idChat": 7,
    "idPregunta": 5,
    "usuario": "manolo",
    "textoPregunta": "Hola que tal" ,
    "feedback": "FALSE"
    
}
#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=filtro&filterBy=user&valor1=manolo&filterBy2=texto_pregunta&valor2=Hola HTTP/1.1

    ///chats/filter?operacion=filtro&filterBy=user&valor1=manolo

#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=rango&filterBy=fecha&valor1=2025-02-05 HTTP/1.1
#######
GET http://localhost:8090/api/rag/v1/chats/filter?operacion=count&filterBy=user&valor1=manolo  HTTP/1.1

#######
GET http://localhost:8090/api/rag/v1/preguntas/filter?operacion=count&filterBy=user&valor1=Usuar2  HTTP/1.1


###
## returnChats
GET http://localhost:8090/api/rag/v1/returnChats? HTTP/1.1
Content-Type: application/json
###

###
##  returnChats con size
GET http://localhost:8090/api/rag/v1/returnChats?size=10 HTTP/1.1
Content-Type: application/json

###
##  returnChats con size
GET http://localhost:8090/api/rag/v1/returnChats?page=1 HTTP/1.1
Content-Type: application/json
######
## #
//return lista de users con distinct
GET http://localhost:8090/api/rag/v1/getListUsuarios HTTP/1.1
Content-Type: application/json